# ==============================================================
# CV Generator – ansible/inventory.ini
# Replace <PUBLIC_IP> with the IP output from: terraform output public_ip
# ==============================================================

[cv_generator]
13.53.205.58 ansible_user=ubuntu ansible_ssh_private_key_file=~/.ssh/cv-generator-key.pem

[cv_generator:vars]
ansible_python_interpreter=/usr/bin/python3
ansible_ssh_common_args='-o StrictHostKeyChecking=no'
